# Generated by Django 4.2 on 2025-06-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_psychologistavailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologistprofile',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
